name: sigmajs
version: 0.1.0
description: >
  Dart wrapper for Sigmajs
author: Nasser Idirene <Nasser.Idirene@acelaworks.com>
homepage: https://github.com/nidirene/sigmajs.dart/

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  build_runner: ^1.2.0
  build_web_compilers: ^1.1.0
  build_test: ^0.10.2+5
  test: ^1.0.0
